---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daanvm-nl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - daanvm.nl
      - www.daanvm.nl
      secretName: daanvm-nl-tls
  rules:
    - host: "daanvm.nl"
      http: &http_rules
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: daanvm-nl
                port:
                  number: 80
    - host: "www.daanvm.nl"
      http: *http_rules
