---
version: '3'
services:
  christelmusic-nl-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    volumes:
      - ./app/public:/usr/share/nginx/html/:delegated
    ports:
      - '8080:80'

  christelmusic-nl-php:
    build:
      context: .
      dockerfile: Dockerfile-php
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/christelmusic.nl/:delegated

  composer-build:
    image: composer:2
    volumes:
      - ./app:/app/:delegated
    command: "composer install --ignore-platform-req ext-imagick"
