---
version: '3'
services:
  daanvm-nl-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html/:delegated
    ports:
      - '8080:80'

  daanvm-nl-php:
    build:
      context: .
      dockerfile: Dockerfile-php
    restart: unless-stopped
    volumes:
      - ./public:/usr/src/daanvm.nl/:delegated
