FROM php:8.2-fpm-alpine as base

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Install php dependencies
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions imagick pcntl

FROM base as builder

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY app/composer.* /usr/src/build/
WORKDIR /usr/src/build
RUN composer install

FROM base

COPY app /usr/src/christelmusic.nl
COPY --from=builder /usr/src/build/vendor /usr/src/christelmusic.nl/vendor
RUN /usr/src/christelmusic.nl/scripts/christelmusic warmup
WORKDIR /usr/src/christelmusic.nl
