---
version: '3.9'
services:
  christelmusic-nl-nginx:
    build:
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    volumes:
      - ./app/public:/usr/share/nginx/html/:delegated
    ports:
      - '8081:80'

  christelmusic-nl-php:
    build:
      dockerfile: Dockerfile-php
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/christelmusic.nl/:delegated

  composer-build:
    build:
      dockerfile: Dockerfile-php
      target: builder
    volumes:
      - ./app:/usr/src/build/:delegated
    command: "composer install"
