---
version: '3.9'
services:
  christelmusic-nl:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - ./app:/var/www/html:delegated
    ports:
      - '8081:80'

  composer-build:
    build:
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./app:/var/www/html:delegated
    command:
      - /bin/sh
      - -c
      - |
        composer install
        /var/www/html/scripts/christelmusic warmup
