<?php declare(strict_types=1);

/** @var Template $this */

use Parable\Framework\Http\Template;

require __DIR__ . '/Includes/header.phtml';

?>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1>Thank you for your order!</h1>
        <p>
            I will personally send you an email to confirm the order and to send
            a payment link.
        </p>
        <p>
            Christel
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-3 offset-md-3">
        <p>
            <img src="/assets/images/jewelcase_landslide.jpg" class="img-fluid"/>
        </p>
    </div>
    <div class="col-md-3">
        <p>
            <img src="/assets/images/jewelcase_watershed.jpg" class="img-fluid"/>
        </p>
    </div>
</div>

<?php require __DIR__ . '/Includes/footer.phtml'; ?>
