#!/usr/bin/env php
<?php declare(strict_types=1);

use ChristelMusic\ConsoleApplication;
use Parable\Di\Container;

require_once __DIR__ . "/../vendor/autoload.php";

$container = new Container();

$application = $container->get(ConsoleApplication::class);
$application->run();
