on:
  push:
    branches:
      - master
      - deploy-strato

jobs:
  build:
    name: Build website zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Build .tar.gz file
        run: |
          docker build --tag local-img/zipper --target zipper .
          docker create --name zipper local-img/zipper
          docker cp zipper:/build.tar.gz ./build.tar.gz
          docker rm -f zipper

      # TODO: remove debug
      - name: Debug print all files
        run: find ${GITHUB_WORKSPACE}
        shell: bash

      # TODO: upload to sftp
