on:
  push:
    branches:
      - master
      - deploy-strato

jobs:
  build:
    name: Build website zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build .tar.gz file
        run: |
          docker build --tag local-img/zipper --target zipper .
          docker create --name zipper local-img/zipper
          docker cp zipper:/build.tar.gz ./build.tar.gz
          docker rm -f zipper
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: build-tar-gz
          path: ./build.tar.gz

  deploy:
    name: Deploy website to Strato
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-tar-gz

      - name: Extract .tar.gz file
        run: |
          tar -xzvf build.tar.gz
          rm build.tar.gz
        shell: bash

      - name: Apt install sshpass
        run: |
          sudo apt-get update
          sudo apt-get -y install sshpass

      - name: Upload to Strato
        env:
          SSHPASS: ${{ secrets.STRATO_SSH_PASSWORD }}
        run: |
          echo "
            $(find . -type d | sed -e 's/^/mkdir /;' | grep -v '^mkdir .$')
            mput -r .
            exit
          " > /tmp/commands.sftp
          sshpass -e sftp -oStrictHostKeyChecking=no -oBatchMode=no -b - "sftp://${{ secrets.STRATO_SSH_USERNAME }}@ssh.strato.com/" < /tmp/commands.sftp
