on:
  push:
    branches:
      - master
      - deploy-strato

jobs:
  build:
    name: Build website zip
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      # TODO: maybe install imagick

      - name: Install dependencies
        uses: php-actions/composer@v4
        with:
          #composer_version: 1
          php_version: 8.0
          working_dir: app

      # TODO: rename from warmup to build, it's no longer a warmup now.
      - name: Run warmup script
        run: ${GITHUB_WORKSPACE}/app/scripts/christelmusic warmup
        shell: bash

      # TODO: remove debug
      - name: Debug print all files
        run: find ${GITHUB_WORKSPACE}
        shell: bash

      # TODO: upload to sftp
